// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgMxZa6LcYpxS5izrhtx4ARccfdlHW2E',
    appId: '1:753761086524:web:68fb4c05471165782ce739',
    messagingSenderId: '753761086524',
    projectId: 'chatapp-b9ddb',
    authDomain: 'chatapp-b9ddb.firebaseapp.com',
    storageBucket: 'chatapp-b9ddb.firebasestorage.app',
    measurementId: 'G-EX1HTJ8ZQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6pxAt0HaDJs6FojjufeO3nxEtL_TKvxg',
    appId: '1:753761086524:android:cb3372ce3f6254f92ce739',
    messagingSenderId: '753761086524',
    projectId: 'chatapp-b9ddb',
    storageBucket: 'chatapp-b9ddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QzrxjhQAvn1xyK86pitK4XZUt38giRg',
    appId: '1:753761086524:ios:867e5fd5e79abd9a2ce739',
    messagingSenderId: '753761086524',
    projectId: 'chatapp-b9ddb',
    storageBucket: 'chatapp-b9ddb.firebasestorage.app',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QzrxjhQAvn1xyK86pitK4XZUt38giRg',
    appId: '1:753761086524:ios:867e5fd5e79abd9a2ce739',
    messagingSenderId: '753761086524',
    projectId: 'chatapp-b9ddb',
    storageBucket: 'chatapp-b9ddb.firebasestorage.app',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgMxZa6LcYpxS5izrhtx4ARccfdlHW2E',
    appId: '1:753761086524:web:7f9e5dbbeefeb96b2ce739',
    messagingSenderId: '753761086524',
    projectId: 'chatapp-b9ddb',
    authDomain: 'chatapp-b9ddb.firebaseapp.com',
    storageBucket: 'chatapp-b9ddb.firebasestorage.app',
    measurementId: 'G-VKQ7R9MV2X',
  );

}